#ifndef CS4323_FINALPROJECT_GROUPC_DATASERVERNETWORK_H
#define CS4323_FINALPROJECT_GROUPC_DATASERVERNETWORK_H

#define DATA_SERVER_ADDRESS "127.0.0.1"
#define DATA_SERVER_PORT 8080

#endif //CS4323_FINALPROJECT_GROUPC_DATASERVERNETWORK_H
