#ifndef CS4323_FINALPROJECT_GROUPC_SERVERTODATASERVERAPI_H
#define CS4323_FINALPROJECT_GROUPC_SERVERTODATASERVERAPI_H

#define REGISTER_COMMAND "|REGISTER|"
#define LOGIN_COMMAND "|LOGIN|"

#endif //CS4323_FINALPROJECT_GROUPC_SERVERTODATASERVERAPI_H
